# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YAVvUkROGM-k8qnj3aBRiEYDCWaDLJ9w
"""

#Importing required library
import numpy as np

#Defining PCA function
def PCA(mat):
    mean = np.mean(mat.T,axis=1)
    cen = mat - mean  #Centering the given matrix
    cov_matrix = np.cov(cen.T)  #Calculating the covariance matrix
    values, vectors = np.linalg.eig(cov_matrix)  #Calculating the Eigen values, Eigen vectors
    print("Eigen values:"),
    print(values)
    print("\nEigen vectors:"),
    print(vectors)
    pc = vectors.T.dot(cen.T)
    print("\nProjection of given matrix:"),
    print(pc.T)

#Calling PCA function
a = np.array([[1,2],[3,4],[5,6]])
PCA(a)